# Extending Logistic Regression: 2015 American Community Survey

## Conrad Appel, Erik Gabrielsen, Danh Nguyen

### Preparation and Overview (30 points total)

[5 points] Explain the task and what business-case or use-case it is designed to solve (or designed to investigate). Detail exactly what the classification task is and what parties would be interested in the results.

[10 points] (mostly the same processes as from lab one) Define and prepare your class variables. Use proper variable representations (int, float, one-hot, etc.). Use pre-processing methods (as needed) for dimensionality reduction, scaling, etc. Remove variables that are not needed/useful for the analysis. Describe the final dataset that is used for classification/regression (include a description of any newly formed variables you created).

[15 points] Divide you data into training and testing data using an 80% training and 20% testing split. Use the cross validation modules that are part of scikit-learn. Argue for or against splitting your data using an 80/20 split. That is, why is the 80/20 split appropriate (or not) for your dataset?  

### Modeling (50 points total)

[20 points] Create a custom, one-versus-all logistic regression classifier using numpy and scipy to optimize. Use object oriented conventions identical to scikit-learn. You should start with the template used in the course. You should add the following functionality to the logistic regression classifier:
Ability to choose optimization technique when class is instantiated: either steepest descent, stochastic gradient descent, or Newton's method. Update the gradient calculation to include a customizable regularization term (either using no regularization, L1 regularization, L2 regularization, or both L1/L2 norm of the weights). Associate a cost with the regularization term, "C", that can be adjusted when the class is instantiated.  

[15 points] Train your classifier to achieve good generalization performance. That is, adjust the optimization technique and the value of the regularization term "C" to achieve the best performance on your test set. Is your method of selecting parameters justified? That is, do you think there is any "data snooping" involved with this method of selecting parameters?

[15 points] Compare the performance of your "best" logistic regression optimization procedure to the procedure used in scikit-learn. Visualize the performance differences in terms of training time, training iterations, and memory usage while training. Discuss the results. 

### Deployment (10 points total)

Which implementation of logistic regression would you advise be used in a deployed machine learning model, your implementation or scikit-learn (or other third party)? Why?

### Exceptional Work (10 points total)

You have free reign to provide additional analyses.
One idea: Make your implementation of logistic regression compatible with the GridSearchCV function that is part of scikit-learn.

## Data Overview

In this lab, we are investigating the relationship between individual income and ...


**Attribute**|**Description**|**Example**
:-----:|:-----:|:-----:
AGEP|Age| 
PINCP|Total person's income (signed)| 
QTRBIR|Quarter of birth|1 - January through March, 2 -  April through June, etc.
JWAP|Time of arrival at work | 
JWDP|Time of departure for work| 
YOEP|Year of entry to the US| 
WAOB|World area of birth| 
RAC1P|Recoded detailed race code|1 - White alone, 2 - Black or African American alone, etc.
MAR|Marital status|1 - Married, 2 - Widowed
MIL|Military Service |1 - Now on active duty, 4 - Never served in the military
SCHL|Educational attainment|23 - Professional degree, 24 - Doctorate degree, etc.
FOD1P|Recoded field of degree|1904 - advertising, 2001 - communication technologies, etc.

In [2]:
## redoing large files
import pandas as pd
import numpy as np

# %time df = pd.read_csv('~/Downloads/ss15pusb.csv') # read in the csv file


In [ ]:
df.columns.values

In [205]:
df.head(10)
df.shape

new_df = df.filter(items=['AGEP','PINCP', 'MAR', 'MIL', 'SCHL','QTRBIR','JWAP','JWDP','YOEP','WAOB','RAC1P', 'FOD1P'])
new_df.shape
# new_df.to_csv('~/Downloads/ss15pusb3.csv')

(1528516, 12)

In [29]:
%time new_df = pd.read_csv('~/Downloads/ss15pusb3.csv') # read in the csv file

CPU times: user 1.78 s, sys: 280 ms, total: 2.06 s
Wall time: 2.1 s


In [30]:
# delete younger than 18
new_df = new_df[new_df.AGEP >= 18]

# find null columns
new_df.columns[new_df.isnull().any()].tolist()

['JWAP', 'JWDP', 'YOEP', 'FOD1P']

In [31]:
#new_df[new_df['JWAP'].isnull()]
# clean out JWAP and JWDP. They are ordinal variables, create a new one to classify them

df_grouped = new_df.groupby(by=['JWAP', 'JWDP'])
# new_df = new_df.groupby(by=['JWAP', 'JWDP']).transform('median')

new_df['JWAP'].fillna(0, inplace=True)
new_df['JWDP'].fillna(0, inplace=True)
new_df['FOD1P'].fillna(0, inplace=True)

## fill null values in YOEP (Year of entrance into US)
new_df['YOEP'].fillna(0, inplace=True)

new_df.columns[new_df.isnull().any()].tolist()

[]

In [32]:
new_df.columns

Index(['Unnamed: 0', 'AGEP', 'PINCP', 'MAR', 'MIL', 'SCHL', 'QTRBIR', 'JWAP',
       'JWDP', 'YOEP', 'WAOB', 'RAC1P', 'FOD1P'],
      dtype='object')

In [33]:
new_df[pd.isnull(new_df).any(axis=1)]
new_df.dropna(inplace=True)
new_df.drop(new_df.columns[0], axis=1, inplace=True)
new_df.head()

AGEP    PINCP  MAR  MIL  SCHL  QTRBIR  JWAP  JWDP  YOEP  WAOB  RAC1P  \
0    77   9100.0    3  4.0  16.0       1   0.0   0.0   0.0     1      1   
1    30   5000.0    1  4.0  11.0       2   0.0   0.0   0.0     1      1   
2    65  20000.0    1  4.0  22.0       4   0.0   0.0   0.0     1      1   
3    69  11000.0    1  4.0  16.0       2   0.0   0.0   0.0     1      1   
4    24  25300.0    1  4.0  21.0       2  82.0  34.0   0.0     1      1   

    FOD1P  
0     0.0  
1     0.0  
2  5404.0  
3     0.0  
4  3600.0

In [34]:
new_df.head()

AGEP    PINCP  MAR  MIL  SCHL  QTRBIR  JWAP  JWDP  YOEP  WAOB  RAC1P  \
0    77   9100.0    3  4.0  16.0       1   0.0   0.0   0.0     1      1   
1    30   5000.0    1  4.0  11.0       2   0.0   0.0   0.0     1      1   
2    65  20000.0    1  4.0  22.0       4   0.0   0.0   0.0     1      1   
3    69  11000.0    1  4.0  16.0       2   0.0   0.0   0.0     1      1   
4    24  25300.0    1  4.0  21.0       2  82.0  34.0   0.0     1      1   

    FOD1P  
0     0.0  
1     0.0  
2  5404.0  
3     0.0  
4  3600.0

In [35]:
new_df['PINCP'] = pd.cut(new_df.PINCP,[0,60000,100000,150000,1e8],5,labels=[0,1,2,3]) # this creates a new variable
# 4. drop rows that still had missing values after grouped imputation
new_df.dropna(inplace=True)
new_df['PINCP'] = new_df['PINCP'].astype(np.int)

In [36]:
for value in new_df.PINCP.unique(): 
    print(len(new_df[new_df['PINCP'] == value]))

864837
48030
136700
37839


In [37]:
new_df.info()
new_df.head()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 1087406 entries, 0 to 1528515
Data columns (total 12 columns):
AGEP      1087406 non-null int64
PINCP     1087406 non-null int64
MAR       1087406 non-null int64
MIL       1087406 non-null float64
SCHL      1087406 non-null float64
QTRBIR    1087406 non-null int64
JWAP      1087406 non-null float64
JWDP      1087406 non-null float64
YOEP      1087406 non-null float64
WAOB      1087406 non-null int64
RAC1P     1087406 non-null int64
FOD1P     1087406 non-null float64
dtypes: float64(6), int64(6)
memory usage: 107.9 MB


AGEP  PINCP  MAR  MIL  SCHL  QTRBIR  JWAP  JWDP  YOEP  WAOB  RAC1P   FOD1P
0    77      0    3  4.0  16.0       1   0.0   0.0   0.0     1      1     0.0
1    30      0    1  4.0  11.0       2   0.0   0.0   0.0     1      1     0.0
2    65      0    1  4.0  22.0       4   0.0   0.0   0.0     1      1  5404.0
3    69      0    1  4.0  16.0       2   0.0   0.0   0.0     1      1     0.0
4    24      0    1  4.0  21.0       2  82.0  34.0   0.0     1      1  3600.0

In [38]:
from sklearn.cross_validation import ShuffleSplit
df_imputed = new_df.copy()
# we want to predict the X and y data as follows:
if 'PINCP' in new_df:
    y = df_imputed['PINCP'].values # get the labels we want
    del df_imputed['PINCP'] # get rid of the class label
    X = df_imputed.values # use everything else to predict!

    ## X and y are now numpy matrices, by calling 'values' on the pandas data frames we
    #    have converted them into simple matrices to use with scikit learn
    
    
# to use the cross validation object in scikit learn, we need to grab an instance
#    of the object and set it up. This object will be able to split our data into 
#    training and testing splits
num_cv_iterations = 1
num_instances = len(y)
cv_object = ShuffleSplit(n=num_instances,
                         n_iter=num_cv_iterations,
                         test_size  = 0.2)
                         
print(cv_object)

ShuffleSplit(1087406, n_iter=1, test_size=0.2, random_state=None)


In [39]:
# run logistic regression and vary some parameters
from sklearn.linear_model import LogisticRegression
from sklearn import metrics as mt

# first we create a reusable logisitic regression object
#   here we can setup the object with different learning parameters and constants
lr_clf = LogisticRegression(penalty='l2', C=1.0, class_weight=None) # get object

# now we can use the cv_object that we setup before to iterate through the 
#    different training and testing sets. Each time we will reuse the logisitic regression 
#    object, but it gets trained on different data each time we use it.

iter_num=0
# the indices are the rows used for training and testing in each iteration
for train_indices, test_indices in cv_object: 
    # I will create new variables here so that it is more obvious what 
    # the code is doing (you can compact this syntax and avoid duplicating memory,
    # but it makes this code less readable)
    X_train = X[train_indices]
    y_train = y[train_indices]
    
    X_test = X[test_indices]
    y_test = y[test_indices]
    
    # train the reusable logisitc regression model on the training data
    lr_clf.fit(X_train,y_train)  # train object
    y_hat = lr_clf.predict(X_test) # get test set precitions

    # now let's get the accuracy and confusion matrix for this iterations of training/testing
    acc = mt.accuracy_score(y_test,y_hat)
    conf = mt.confusion_matrix(y_test,y_hat)
    print("====Iteration",iter_num," ====")
    print("accuracy", acc )
    print("confusion matrix\n",conf)
    iter_num+=1
    
# Also note that every time you run the above code
#   it randomly creates a new training and testing set, 
#   so accuracy will be different each time

====Iteration 0  ====
accuracy 0.79457610285
confusion matrix
 [[171207   1677      0      0]
 [ 25648   1597      1      0]
 [  8556   1110      2      0]
 [  6487   1196      1      0]]


In [40]:
# confusion matrix accuracy per class
for i in range(0,len(conf)):
    print("Accuracy for income bracket ", i, "=",conf[i][i]/sum(conf[i]))

Accuracy for income bracket  0 = 0.990299854238
Accuracy for income bracket  1 = 0.058614108493
Accuracy for income bracket  2 = 0.000206868018204
Accuracy for income bracket  3 = 0.0


In [47]:
import numpy as np
import pandas as p
from scipy.optimize import fmin_bfgs
from scipy.special import expit
from sklearn.model_selection import GridSearchCV
from sklearn.utils.estimator_checks import check_estimator
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

ImportError: No module named 'sklearn.model_selection'

In [42]:
class BinaryClassifierBase:
    def __init__(self, eta, iterations=20, cost=0.001, norm=2):
        self.eta = eta
        self.cost = cost
        self.iters = iterations
        self.norm = norm
    
    def normalize(self, w, gradient):
        # regularization (does both if 3)
        if self.norm & 1: # L1 norm
            gradient[1:] += -1 * w[1:] * self.cost
        elif self.norm & 2: # L2 norm
            gradient[1:] += -2 * w[1:] * self.cost
    
    def fit(self, x, y):
        self.w_ = np.zeros((x.shape[1],1))
        for _ in range(self.iters):
            gradient = self._get_gradient(x,y)
            self.normalize(self.w_, gradient)
            self.w_ += gradient*self.eta
    
    def predict_proba(self,x):
        return 1/(1+np.exp(-(x @ self.w_)))
    
    def predict(self, x):
        return (self.predict_proba(x)>0.5)
    
    
class BinaryStochDescClassifier(BinaryClassifierBase):
    def _get_gradient(self, x, y):
        idx = int(np.random.rand()*len(y)) # grab random instance
        ydiff = y[idx]-self.predict_proba(x[idx]) # get y difference (now scalar)
        gradient = x[idx] * ydiff[:,np.newaxis] # make ydiff a column vector and multiply through
        gradient = gradient.reshape(self.w_.shape)
        return gradient
    
    
class BinarySteepDescClassifier(BinaryClassifierBase):
    def _get_gradient(self, x, y):
        ydiff = y-self.predict_proba(x).ravel()
        gradient = np.mean(x * ydiff[:,np.newaxis], axis=0)
        return gradient.reshape(self.w_.shape)

    
class BinaryNewtonClassifier(BinaryClassifierBase):
    def fit(self, x, y):
        def obj_fn(w, x, y, c):
            g = expit(x @ w)
            return -np.sum(np.log(g[y==1]))-np.sum(np.log(1-g[y==0])) + c*sum(w**2)
        
        def obj_grad(w, x, y, c):
            g = expit(x @ w)
            ydiff = y-g
            gradient = np.mean(x * ydiff[:,np.newaxis], axis=0)
            gradient = gradient.reshape(w.shape)
            self.normalize(w, gradient)
            return -gradient
        
        self.w_ = fmin_bfgs(obj_fn, 
                            np.zeros((x.shape[1], 1)), 
                            fprime=obj_grad, 
                            args=(x, y, self.cost), 
                            gtol=1e-03, 
                            maxiter=self.iters,
                            disp=False).reshape((x.shape[1], 1))

        
class LogRegClassifier:
    def __init__(self, eta, iterations=20, optimize='steepdesc', cost=0.001, norm=2):
        typesofoptimize = {
            'steepdesc': BinarySteepDescClassifier, 
            'stochdesc': BinaryStochDescClassifier, 
            'newton': BinaryNewtonClassifier
        }
        if optimize not in typesofoptimize.keys():
            raise ValueError('optimize must be one of: ' + ' '.join(typesofoptimize.keys()))
        
        self.eta = eta
        self.iters = iterations
        self.optimize = optimize
        self.classifier = typesofoptimize[optimize]
        self.cost = cost
        self.norm = norm
        self.classifiers = [] # fill with binary classifiers during fit
    
    def _add_bias(self, x):
        return np.hstack((np.ones((x.shape[0],1)),x))
    
    def fit(self, x, y):
        Xb = self._add_bias(x)
        classes = np.unique(y)
        
        for cl in classes:
            cur_y = y==cl
            cur_classifier = self.classifier(self.eta, self.iters, cost=self.cost, norm=self.norm)
            cur_classifier.fit(x, cur_y)
            self.classifiers.append(cur_classifier)
    
    def predict(self, x):
        if not self.classifiers:
            raise RuntimeError('Classifier not fit!')
        
        probabilities = []
        for classifier in self.classifiers:
            probabilities.append(classifier.predict_proba(x))
        probabilities = np.hstack(probabilities)
        return np.argmax(probabilities,axis=1)

In [44]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
ds = load_iris()
kwargs = {
    'norm': 2,
    'cost': .1,
    'iterations': 500
}
regrs = {
    'newton': LogRegClassifier(.1, optimize='newton', **kwargs),
    'stoch': LogRegClassifier(.1, optimize='stochdesc', **kwargs), # Different results every time, random
    'steep': LogRegClassifier(.1, optimize='steepdesc', **kwargs)
}
for regr in regrs.values():
    regr.fit(ds.data, ds.target)

for key, val in regrs.items():
    res = val.predict(ds.data)
    print(key + ': ' +str(accuracy_score(ds.target, res)))

stoch: 0.64
steep: 0.813333333333
newton: 0.813333333333


In [45]:
X_train = X[train_indices]
y_train = y[train_indices]

X_test = X[test_indices]
y_test = y[test_indices]

kwargs = {
    'norm': 2,
    'cost': .1,
    'iterations': 500
}

lr = LogRegClassifier(.1, optimize='steepdesc', **kwargs)
lr.fit(X_train,y_train)
print(lr)

yhat = lr.predict(X_test)

print('Accuracy of: ',accuracy_score(y_test,yhat))

Accuracy of:  0.794934753221


In [46]:
class LogRegClassifier:
    def __init__(self, eta=.0001, iters=20, optimize='steepdesc', cost=0.001, norm=2):
        self._set_optimization(optimize)
        self.eta = eta
        self.iters = iters
        self.cost = cost
        self.norm = norm
        
        self.classifiers = [] # fill with binary classifiers during fit
        self._estimator_type = 'classifier'
    
    def _add_bias(self, x):
        return np.hstack((np.ones((x.shape[0],1)),x))
    
    def _set_optimization(self, optimize):
        typesofoptimize = {
            'steepdesc': BinarySteepDescClassifier, 
            'stochdesc': BinaryStochDescClassifier, 
            'newton': BinaryNewtonClassifier
        }
        if optimize not in typesofoptimize.keys():
            raise ValueError('optimize must be one of: ' + ' '.join(typesofoptimize.keys()))
            
        self.optimize = optimize
        self.classifier = typesofoptimize[optimize]
        
    def fit(self, x, y):
        x, y = check_X_y(x, y)
        
        Xb = self._add_bias(x)
        self.classes_ = np.unique(y)
        self.X_ = x
        self.y_ = y
        
        for cl in self.classes_:
            cur_y = y==cl
            cur_classifier = self.classifier(self.eta, self.iters, cost=self.cost, norm=self.norm)
            cur_classifier.fit(x, cur_y)
            self.classifiers.append(cur_classifier)
        return self
    
    def predict(self, x):
        check_is_fitted(self, ['X_', 'y_'])
        x = check_array(x)
        
        probabilities = []
        for classifier in self.classifiers:
            probabilities.append(classifier.predict_proba(x))
        probabilities = np.hstack(probabilities)
        return np.argmax(probabilities,axis=1)
    
    def score(self, x, y):
        res = self.predict(x)
        return accuracy_score(y, res)
    
    def set_params(self, **parameters):
        for parameter, value in parameters.items():
            setattr(self, parameter, value)
        return self
            
    def get_params(self, deep=True):
        return {
            'eta': self.eta,
            'iters': self.iters,
            'optimize': self.optimize,
            'cost': self.cost,
            'norm': self.norm
        }
    
# check_estimator(LogRegClassifier)

import numpy as np
import pandas as p
from scipy.optimize import fmin_bfgs
from scipy.special import expit
from sklearn.model_selection import GridSearchCV
from sklearn.utils.estimator_checks import check_estimator
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.metrics import accuracy_score

params = {
    "optimize": ['newton', 'stochdesc', 'steepdesc'],
    "eta": [.0001, .001, .01, .1, .25, .5],
    "norm": [0, 1, 2, 3],
    "cost": [.0001, .001, .01, .1, .25, .5]
}
cv = GridSearchCV(LogRegClassifier(), params, n_jobs=-1)
cv.fit(X_train, y_train)
print('Best score: '+str(cv.best_score_))
print(cv.best_params_)

ImportError: No module named 'sklearn.model_selection'