# Lab 04

## Conrad Appel, Erik Gabrielsen, Danh Nguyen

### Preparation and Overview (30 points total)

[5 points] Explain the task and what business-case or use-case it is designed to solve (or designed to investigate). Detail exactly what the classification task is and what parties would be interested in the results.

[10 points] (mostly the same processes as from lab one) Define and prepare your class variables. Use proper variable representations (int, float, one-hot, etc.). Use pre-processing methods (as needed) for dimensionality reduction, scaling, etc. Remove variables that are not needed/useful for the analysis. Describe the final dataset that is used for classification/regression (include a description of any newly formed variables you created).

[15 points] Divide you data into training and testing data using an 80% training and 20% testing split. Use the cross validation modules that are part of scikit-learn. Argue for or against splitting your data using an 80/20 split. That is, why is the 80/20 split appropriate (or not) for your dataset?  

### Modeling (50 points total)

[20 points] Create a custom, one-versus-all logistic regression classifier using numpy and scipy to optimize. Use object oriented conventions identical to scikit-learn. You should start with the template used in the course. You should add the following functionality to the logistic regression classifier:
Ability to choose optimization technique when class is instantiated: either steepest descent, stochastic gradient descent, or Newton's method. Update the gradient calculation to include a customizable regularization term (either using no regularization, L1 regularization, L2 regularization, or both L1/L2 norm of the weights). Associate a cost with the regularization term, "C", that can be adjusted when the class is instantiated.  

[15 points] Train your classifier to achieve good generalization performance. That is, adjust the optimization technique and the value of the regularization term "C" to achieve the best performance on your test set. Is your method of selecting parameters justified? That is, do you think there is any "data snooping" involved with this method of selecting parameters?

[15 points] Compare the performance of your "best" logistic regression optimization procedure to the procedure used in scikit-learn. Visualize the performance differences in terms of training time, training iterations, and memory usage while training. Discuss the results. 

### Deployment (10 points total)

Which implementation of logistic regression would you advise be used in a deployed machine learning model, your implementation or scikit-learn (or other third party)? Why?

### Exceptional Work (10 points total)

You have free reign to provide additional analyses.
One idea: Make your implementation of logistic regression compatible with the GridSearchCV function that is part of scikit-learn.

In [3]:
## redoing large files
import pandas as pd
import numpy as np

# %time df = pd.read_csv('~/Downloads/ss15pusb.csv') # read in the csv file


In [ ]:
df.columns.values

In [ ]:
df.drop_duplicates()

In [ ]:
df.head(10)
df.shape

new_df = df.filter(items=['AGEP','PINCP','QTRBIR','JWAP','JWDP','YOEP','WAOB','RAC1P'])
new_df.shape
new_df.to_csv('~/Downloads/ss15pusb2.csv')

In [4]:

%time new_df = pd.read_csv('~/Downloads/ss15pusb2.csv') # read in the csv file

CPU times: user 1.77 s, sys: 236 ms, total: 2.01 s
Wall time: 2.25 s


In [5]:
# delete younger than 18
new_df = new_df[new_df.AGEP >= 18]

# find null columns
new_df.columns[new_df.isnull().any()].tolist()

['JWAP', 'JWDP', 'YOEP']

In [6]:
#new_df[new_df['JWAP'].isnull()]
# clean out JWAP and JWDP

df_grouped = new_df.groupby(by=['JWAP', 'JWDP'])
new_df = new_df.groupby(by=['JWAP', 'JWDP']).transform('median')

## fill null values in YOEP (Year of entrance into US)
new_df['YOEP'].fillna(0, inplace=True)

new_df.columns[new_df.isnull().any()].tolist()

[]

In [7]:
new_df[pd.isnull(new_df).any(axis=1)]
new_df.dropna(inplace=True)
new_df.drop(new_df.columns[0], axis=1, inplace=True)
new_df.head()

AGEP    PINCP  QTRBIR    YOEP  WAOB  RAC1P
0   0.0      0.0     0.0     0.0   0.0    0.0
1   0.0      0.0     0.0     0.0   0.0    0.0
2   0.0      0.0     0.0     0.0   0.0    0.0
3   0.0      0.0     0.0     0.0   0.0    0.0
4  46.0  50000.0     3.0  1991.0   1.0    1.0

In [9]:
new_df['PINCP'] = pd.cut(new_df.PINCP,[0,20000,60000,100000,150000,1e8],5,labels=[0,1,2,3,4]) # this creates a new variable
# 4. drop rows that still had missing values after grouped imputation
new_df.dropna(inplace=True)
new_df['PINCP'] = new_df['PINCP'].astype(np.int)

In [10]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 650652 entries, 4 to 1528515
Data columns (total 6 columns):
AGEP      650652 non-null float64
PINCP     650652 non-null int64
QTRBIR    650652 non-null float64
YOEP      650652 non-null float64
WAOB      650652 non-null float64
RAC1P     650652 non-null float64
dtypes: float64(5), int64(1)
memory usage: 34.7 MB


In [11]:
from sklearn.cross_validation import ShuffleSplit
df_imputed = new_df.copy()
# we want to predict the X and y data as follows:
if 'PINCP' in new_df:
    y = df_imputed['PINCP'].values # get the labels we want
    del df_imputed['PINCP'] # get rid of the class label
    X = df_imputed.values # use everything else to predict!

    ## X and y are now numpy matrices, by calling 'values' on the pandas data frames we
    #    have converted them into simple matrices to use with scikit learn
    
    
# to use the cross validation object in scikit learn, we need to grab an instance
#    of the object and set it up. This object will be able to split our data into 
#    training and testing splits
num_cv_iterations = 3
num_instances = len(y)
cv_object = ShuffleSplit(n=num_instances,
                         n_iter=num_cv_iterations,
                         test_size  = 0.2)
                         
print(cv_object)

ShuffleSplit(650652, n_iter=3, test_size=0.2, random_state=None)


In [12]:
# run logistic regression and vary some parameters
from sklearn.linear_model import LogisticRegression
from sklearn import metrics as mt

# first we create a reusable logisitic regression object
#   here we can setup the object with different learning parameters and constants
lr_clf = LogisticRegression(penalty='l2', C=1.0, class_weight=None) # get object

# now we can use the cv_object that we setup before to iterate through the 
#    different training and testing sets. Each time we will reuse the logisitic regression 
#    object, but it gets trained on different data each time we use it.

iter_num=0
# the indices are the rows used for training and testing in each iteration
for train_indices, test_indices in cv_object: 
    # I will create new variables here so that it is more obvious what 
    # the code is doing (you can compact this syntax and avoid duplicating memory,
    # but it makes this code less readable)
    X_train = X[train_indices]
    y_train = y[train_indices]
    
    X_test = X[test_indices]
    y_test = y[test_indices]
    
    # train the reusable logisitc regression model on the training data
    lr_clf.fit(X_train,y_train)  # train object
    y_hat = lr_clf.predict(X_test) # get test set precitions

    # now let's get the accuracy and confusion matrix for this iterations of training/testing
    acc = mt.accuracy_score(y_test,y_hat)
    conf = mt.confusion_matrix(y_test,y_hat)
    print("====Iteration",iter_num," ====")
    print("accuracy", acc )
    print("confusion matrix\n",conf)
    iter_num+=1
    
# Also note that every time you run the above code
#   it randomly creates a new training and testing set, 
#   so accuracy will be different each time

====Iteration 0  ====
accuracy 0.963083354466
confusion matrix
 [[  4987   2433      0      0      0]
 [   526 120340      0      0      0]
 [     5   1782      0      0      0]
 [     3     37      0      0      0]
 [     0     18      0      0      0]]
====Iteration 1  ====
accuracy 0.963260099438
confusion matrix
 [[  5118   2454      0      0      0]
 [   530 120231      0      0      0]
 [     8   1727      1      0      0]
 [     2     32      0      0      0]
 [     0     28      0      0      0]]
====Iteration 2  ====
accuracy 0.961815401403
confusion matrix
 [[  4837   2622      0      0      0]
 [   564 120325      0      0      0]
 [     9   1718      0      0      0]
 [     2     35      0      0      0]
 [     0     19      0      0      0]]


In [ ]:
import numpy as np
import pandas as p
from scipy.optimize import fmin_bfgs
from scipy.special import expit

In [ ]:
class BinaryClassifierBase:
    def __init__(self, eta, iterations=20, cost=0.001):
        self.eta = eta
        self.cost = cost
        self.iters = iterations
    
    def fit(self, x, y):
        self.w_ = np.zeros((x.shape[1],1))
        for _ in range(self.iters):
            gradient = self._get_gradient(x,y)
            self.w_ += gradient*self.eta
    
    def predict_proba(self,x):
        return 1/(1+np.exp(-(x @ self.w_)))
    
    def predict(self, x):
        return (self.predict_proba(x)>0.5)
    
    
class BinaryStochDescClassifier(BinaryClassifierBase):
    def _get_gradient(self, x, y):
        idx = int(np.random.rand()*len(y)) # grab random instance
        ydiff = y[idx]-self.predict_proba(x[idx]) # get y difference (now scalar)
        gradient = x[idx] * ydiff[:,np.newaxis] # make ydiff a column vector and multiply through
        gradient = gradient.reshape(self.w_.shape)
        gradient[1:] += -2 * self.w_[1:] * self.cost
        return gradient
    
    
class BinarySteepDescClassifier(BinaryClassifierBase):
    def _get_gradient(self, x, y):
        ydiff = y-self.predict_proba(x).ravel()
        gradient = np.mean(x * ydiff[:,np.newaxis], axis=0)
        return gradient.reshape(self.w_.shape)

    
class BinaryNewtonClassifier(BinaryClassifierBase):
    def fit(self, x, y):
        def obj_fn(w, x, y, c):
            g = expit(x @ w)
            return -np.sum(np.log(g[y==1]))-np.sum(np.log(1-g[y==0])) + c*sum(w**2)
        
        def obj_grad(w, x, y, c):
            g = expit(x @ w)
            ydiff = y-g
            gradient = np.mean(x * ydiff[:,np.newaxis], axis=0)
            gradient = gradient.reshape(w.shape)
            gradient[1:] += -2 * w[1:] * c
            return -gradient
        
        self.w_ = fmin_bfgs(obj_fn, 
                            np.zeros((x.shape[1], 1)), 
                            fprime=obj_grad, 
                            args=(x, y, self.cost), 
                            gtol=1e-03, 
                            maxiter=self.iters, 
                            disp=False).reshape((x.shape[1], 1))

        
class LogRegClassifier:
    def __init__(self, eta, iterations=20, optimize='steepdesc', cost=0.001):
        typesofoptimize = {
            'steepdesc': BinarySteepDescClassifier, 
            'stochdesc': BinaryStochDescClassifier, 
            'newton': BinaryNewtonClassifier
        }
        if optimize not in typesofoptimize.keys():
            raise ValueError('optimize must be one of: ' + ' '.join(typesofoptimize.keys()))
        
        self.eta = eta
        self.iters = iterations
        self.optimize = optimize
        self.classifier = typesofoptimize[optimize]
        self.cost = cost
        self.classifiers = [] # fill with binary classifiers during fit
    
    def _add_bias(self, x):
        return np.hstack((np.ones((x.shape[0],1)),x))
    
    def fit(self, x, y):
        Xb = self._add_bias(x)
        classes = np.unique(y)
        
        for cl in classes:
            cur_y = y==cl
            cur_classifier = self.classifier(self.eta, self.iters, cost=self.cost)
            cur_classifier.fit(x, cur_y)
            self.classifiers.append(cur_classifier)
    
    def predict(self, x):
        if not self.classifiers:
            raise RuntimeError('Classifier not fit!')
        
        probabilities = []
        for classifier in self.classifiers:
            probabilities.append(classifier.predict_proba(x))
        probabilities = np.hstack(probabilities)
        return np.argmax(probabilities,axis=1)

In [ ]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
ds = load_iris()
regrs = {
    'newton': LogRegClassifier(.1, 500, optimize='newton'),
    'stoch': LogRegClassifier(.1, 500, optimize='stochdesc'), # Different results every time, random
    'steep': LogRegClassifier(.1, 500, optimize='steepdesc')
}
for regr in regrs.values():
    regr.fit(ds.data, ds.target)

for key, val in regrs.items():
    res = val.predict(ds.data)
    print(key + ': ' +str(accuracy_score(ds.target, res)))